# $FreeBSD$
    COMMENT = "David's uncommited ports"

    SUBDIR += OpenNetAdmin-build_bind
    SUBDIR += OpenNetAdmin-build_isc_dhcp
    SUBDIR += OpenNetAdmin-dcm
    SUBDIR += OpenNetAdmin-ona
    SUBDIR += PowerDNS-Admin
    SUBDIR += ixnas-api
    SUBDIR += mod_auth_pubtkt_ix
    SUBDIR += vm-bhyve-iscsi
